version: '3.7'
services:
  mysql:
    container_name: mysql
    ports:
      - '3307:3306'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: prisma
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: api/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma
  api:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: api
    ports:
      - '4000:4000'
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/prisma
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes: #define our mysql volume used above
  mysql:
